import json
import os

# Configuration
base_dir = r"D:\Usuarios\Luis Macias\Documentos\Proyectos\AnvilCraft\reports\vanilla_1.21.10"
output_dir = r"D:\Usuarios\Luis Macias\Documentos\Proyectos\AnvilCraft\src\lib\data"
output_args_path = os.path.join(output_dir, "arguments.json")
output_tree_path = os.path.join(output_dir, "command_tree.json")

# Arguments Structure
arguments = {
    # Initialize with static selectors for entity parsers
    "minecraft:entity": ["@a", "@p", "@e", "@s", "@r"],
    "minecraft:game_profile": ["@a", "@p", "@e", "@s", "@r"]
}

# 1. Blocks
try:
    with open(os.path.join(base_dir, "blocks.json"), "r") as f:
        data = json.load(f)
        keys = list(data.keys())
        arguments["minecraft:block_state"] = keys
        arguments["minecraft:block_predicate"] = keys
        print(f"Extracted {len(keys)} blocks")
except Exception as e:
    print(f"Failed to extract blocks: {e}")

# 2. Items
try:
    with open(os.path.join(base_dir, "items.json"), "r") as f:
        data = json.load(f)
        keys = list(data.keys())
        arguments["minecraft:item_stack"] = keys
        arguments["minecraft:item_predicate"] = keys
        print(f"Extracted {len(keys)} items")
except Exception as e:
    print(f"Failed to extract items: {e}")

# 3. Registries
try:
    with open(os.path.join(base_dir, "registries.json"), "r") as f:
        data = json.load(f)

        def extract_registry(registry_key, argument_keys):
            if registry_key in data:
                entries = list(data[registry_key]["entries"].keys())
                for arg_key in argument_keys:
                    arguments[arg_key] = entries
                print(f"Extracted {len(entries)} from {registry_key}")

        extract_registry("minecraft:biome", ["minecraft:biome", "minecraft:resource_or_tag"])
        extract_registry("minecraft:enchantment", ["minecraft:enchantment"])
        extract_registry("minecraft:mob_effect", ["minecraft:mob_effect"])
        extract_registry("minecraft:entity_type", ["minecraft:entity_summon", "minecraft:resource"])
        extract_registry("minecraft:attribute", ["minecraft:attribute"])
        extract_registry("minecraft:potion", ["minecraft:potion"])
        extract_registry("minecraft:sound_event", ["minecraft:resource_location", "minecraft:sound"]) # Sound is often resource_location
        extract_registry("minecraft:particle_type", ["minecraft:particle"])
        extract_registry("minecraft:dimension", ["minecraft:dimension"])

        print("Extracted registries")
        
except Exception as e:
    print(f"Failed to extract registries: {e}")

# 4. Command Tree Generation (commands.json)
def build_command_tree(commands_data):
    # The vanilla commands.json is a flat list of nodes, not a nested tree.
    # We need to reconstruct the tree starting from the root node.
    # But usually the vanilla report IS a graph where nodes reference children by index or name?
    # Actually, the standard format (generated by data generator) is a tree where:
    # Root node has 'children' dictionary.
    # Let's verify the structure. If it's the standard Brigadier serialization:
    # { "type": "root", "children": { "cmd": { ... } } }
    
    # Let's assume standard Brigadier JSON format.
    
    root = commands_data
    
    # Function to simplify the tree
    def simplify_node(node):
        simplified = {
            "type": node.get("type", "literal")
        }
        
        # If argument, extract parser
        if simplified["type"] == "argument":
            simplified["parser"] = node.get("parser", "brigadier:string")
            # You might want to extract properties here if needed (min, max, etc)
        
        # Process Children
        if "children" in node:
            simplified["children"] = {}
            for name, child_node in node["children"].items():
                simplified["children"][name] = simplify_node(child_node)
        
        # Handling Redirects (aliases)
        # If a node is a redirect, it points to another node. 
        # For simplicity in frontend, we might just want to 'copy' the target or ignore?
        # The frontend recursive logic might hang if we have loops, but redirects usually point to root or specific subcommands.
        # Brigadier JSON usually resolves structure fully or uses 'redirect' property which points to an index in a flat array (if flat) or path?
        # Standard recursive JSON (like we see in most reports) nests children.
        # If 'redirect' exists, it means "after this, go there".
        # We will ignore redirects for the simple autocomplete for now, or treat as leaf.
        
        return simplified

    return simplify_node(root)

try:
    with open(os.path.join(base_dir, "commands.json"), "r") as f:
        commands_data = json.load(f)
        
        print("Parsing command tree...")
        simple_tree = build_command_tree(commands_data)
        
        with open(output_tree_path, "w") as out:
            json.dump(simple_tree, out, separators=(',', ':'))
        
        print(f"Saved command tree to {output_tree_path}")

except Exception as e:
    print(f"Failed to extract command tree: {e}")


# Save Arguments
with open(output_args_path, "w") as f:
    json.dump(arguments, f, separators=(',', ':'))

print(f"Saved arguments to {output_args_path}")
