//! Mods-family loaders (NeoForge, Forge, Fabric, Quilt).
//!
//! NeoForge is the only loader in the project that uses the
//! `is_two_step_version()` flow: the user first picks an MC version, then
//! picks a NeoForge build for that MC version. The other three are
//! single-step (one version id → one install).
//!
//! `find_forge_args_file` lives here as `pub(crate)` because both
//! `start_instance` (in `commands/server.rs`) and the launch flow need to
//! detect the NeoForge/Forge `@args.txt` launch pattern.

use async_trait::async_trait;
use std::fs;
use std::io::Write as IoWrite;
use std::path::{Path, PathBuf};
use tauri::Emitter;

#[cfg(windows)]
use std::os::windows::process::CommandExt;

use crate::loaders::common::{download_file, write_eula_txt};
use crate::loaders::types::{DownloadInfo, VersionMeta};
use crate::loaders::{LoaderCapabilities, LoaderCategory, LoaderStrategy};
use crate::models::{InstanceEngine, InstanceInstallProgress};

// ── Shared capabilities ────────────────────────────────────────────────────

fn mods_capabilities() -> LoaderCapabilities {
    LoaderCapabilities {
        supports_plugins: false,
        supports_mods: true,
        is_proxy: false,
        custom_url_supported: true,
    }
}

fn not_implemented_yet(name: &str) -> String {
    format!("{} version fetching is not yet implemented", name)
}

// ── `find_forge_args_file` (moved from `commands/server.rs`) ───────────────

/// Searches inside `mc_dir/libraries/` recursively for the platform-specific
/// args file generated by the NeoForge or Forge installer:
///   - Windows: `win_args.txt`
///   - Unix:    `unix_args.txt`
///
/// Returns `Some(absolute_path)` if found, otherwise `None` (classic launch).
pub(crate) fn find_forge_args_file(mc_dir: &Path) -> Option<PathBuf> {
    #[cfg(windows)]
    let target_name = "win_args.txt";
    #[cfg(not(windows))]
    let target_name = "unix_args.txt";

    // Forge 1.21.x installs `win_args.txt` (or `unix_args.txt`) at the top of
    // `mc_dir/` rather than inside `mc_dir/libraries/...`. Probe the new
    // location first, then fall back to the recursive search in `libraries/`
    // (NeoForge + Forge ≤ 1.20.x behaviour). Without this, server start would
    // silently downgrade to `java -jar server.jar` and Forge 1.21.x would not
    // boot (the shim jar — invoked via `@win_args.txt` — is what wires up the
    // classpath).
    let top_level = mc_dir.join(target_name);
    if top_level.exists() {
        return Some(top_level);
    }

    let libs_dir = mc_dir.join("libraries");
    if !libs_dir.exists() {
        return None;
    }

    fn walk(dir: &Path, target: &str, depth: u8) -> Option<PathBuf> {
        if depth == 0 {
            return None;
        }
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    if let Some(found) = walk(&path, target, depth - 1) {
                        return Some(found);
                    }
                } else if path.file_name().map_or(false, |n| n == target) {
                    return Some(path);
                }
            }
        }
        None
    }

    walk(&libs_dir, target_name, 8)
}

// ═══════════════════════════════════════════════════════════════════════════
//  NeoForge (full impl: 2-step version + installer child process)
// ═══════════════════════════════════════════════════════════════════════════

/// Extract the "Minecraft version" category from a NeoForge version string.
fn extract_neoforge_category(nf_version: &str) -> Option<String> {
    if nf_version.starts_with("1.") {
        nf_version.split('-').next().map(|s| s.to_string())
    } else {
        let parts: Vec<&str> = nf_version.split('.').collect();
        if parts.len() >= 2 {
            let major = parts[0].parse::<u32>().unwrap_or(0);
            if major >= 20 && major <= 21 {
                Some(format!("1.{}.{}", parts[0], parts[1]))
            } else {
                let cat = parts[0..parts.len() - 1].join(".");
                Some(cat)
            }
        } else {
            None
        }
    }
}

/// Fetch the maven-metadata.xml once and return its body.
async fn fetch_neoforge_maven_metadata() -> Result<String, String> {
    let url = "https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml";
    let client = reqwest::Client::builder()
        .user_agent("AnvilCraft/1.0")
        .timeout(std::time::Duration::from_secs(30))
        .build()
        .map_err(|e| e.to_string())?;
    client
        .get(url)
        .send()
        .await
        .map_err(|e| format!("Network error: {}", e))?
        .text()
        .await
        .map_err(|e| e.to_string())
}

/// Step 1 of the NeoForge flow: list MC versions that have at least one build.
fn parse_mc_versions_from_xml(xml: &str) -> Vec<String> {
    let mut mc_versions: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for line in xml.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("<version>") && trimmed.ends_with("</version>") {
            let inner = trimmed
                .trim_start_matches("<version>")
                .trim_end_matches("</version>");
            if let Some(ver) = extract_neoforge_category(inner) {
                if ver.split('.').all(|p| p.parse::<u32>().is_ok()) {
                    mc_versions.insert(ver);
                }
            }
        }
    }
    let mut result: Vec<String> = mc_versions.into_iter().collect();
    result.reverse();
    result
}

/// Step 2 of the NeoForge flow: list NeoForge builds for an MC version.
fn parse_builds_from_xml(xml: &str, mc_version: &str, betas: bool) -> Vec<String> {
    let mut versions: Vec<String> = Vec::new();
    for line in xml.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("<version>") && trimmed.ends_with("</version>") {
            let inner = trimmed
                .trim_start_matches("<version>")
                .trim_end_matches("</version>");
            if let Some(ver) = extract_neoforge_category(inner) {
                if ver == mc_version {
                    let is_beta = inner.contains("-beta");
                    if betas || !is_beta {
                        versions.push(inner.to_string());
                    }
                }
            }
        }
    }
    versions.reverse();
    versions
}

/// Run the NeoForge installer JAR headlessly and stream stderr/stdout as
/// `install-progress` events. Emits Done on success.
async fn run_neoforge_installer(
    app: &tauri::AppHandle,
    id: &str,
    neoforge_version: &str,
    minecraft_dir: &Path,
) -> Result<(), String> {
    let installer_url = format!(
        "https://maven.neoforged.net/releases/net/neoforged/neoforge/{}/neoforge-{}-installer.jar",
        neoforge_version, neoforge_version
    );
    let installer_path = minecraft_dir.join(format!("neoforge-{}-installer.jar", neoforge_version));
    fs::create_dir_all(minecraft_dir).map_err(|e| e.to_string())?;

    let _ = app.emit(
        "install-progress",
        InstanceInstallProgress {
            id: id.to_string(),
            step: format!("Downloading NeoForge {} installer...", neoforge_version),
            progress: 0,
            total_size: None,
            downloaded: 0,
        },
    );

    let log_file = minecraft_dir
        .parent()
        .unwrap_or(minecraft_dir)
        .join("install.log");

    download_file(app, &installer_url, &installer_path, id, None, Some(&log_file)).await?;

    let _ = app.emit(
        "install-progress",
        InstanceInstallProgress {
            id: id.to_string(),
            step: format!("Ejecutando instalador NeoForge {}...", neoforge_version),
            progress: 50,
            total_size: None,
            downloaded: 0,
        },
    );

    if let Ok(mut f) = fs::OpenOptions::new().append(true).open(&log_file) {
        let _ = writeln!(
            f,
            "[{}] Running NeoForge installer headlessly...",
            chrono::Local::now().format("%H:%M:%S")
        );
    }

    let java_exe = crate::commands::java::find_any_java_executable(app).ok_or_else(|| {
        "Java not found. Install a Java runtime from Settings \u{2192} Portable Java, or set the JAVA_HOME environment variable.".to_string()
    })?;
    let mut std_cmd = std::process::Command::new(&java_exe);
    std_cmd
        .arg("-jar")
        .arg(&installer_path)
        .arg("--installServer")
        .current_dir(minecraft_dir)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped());

    #[cfg(windows)]
    std_cmd.creation_flags(0x08000000);

    let mut cmd = tokio::process::Command::from(std_cmd);
    let mut child = cmd
        .spawn()
        .map_err(|e| format!("Failed to run NeoForge installer: {}", e))?;

    let app_for_stderr = app.clone();
    let id_for_stderr = id.to_string();
    let stderr_log = log_file.clone();
    let stderr_handle = if let Some(stderr) = child.stderr.take() {
        Some(tokio::spawn(async move {
            use tokio::io::AsyncBufReadExt;
            let mut reader = tokio::io::BufReader::new(stderr).lines();
            let mut line_count: u64 = 0;
            while let Ok(Some(line)) = reader.next_line().await {
                line_count += 1;
                if let Ok(mut f) = fs::OpenOptions::new().append(true).open(&stderr_log) {
                    let _ = writeln!(f, "[STDERR] {}", line);
                }
                if line_count % 3 == 0 || line.contains("Complete") || line.contains("Installing") {
                    let mut short_line = line.clone();
                    if short_line.len() > 60 {
                        short_line.truncate(60);
                        short_line.push_str("...");
                    }
                    let simulated_progress = 50 + (line_count.min(180) / 4);
                    let _ = app_for_stderr.emit(
                        "install-progress",
                        InstanceInstallProgress {
                            id: id_for_stderr.clone(),
                            step: format!("NeoForge: {}", short_line),
                            progress: simulated_progress as u64,
                            total_size: None,
                            downloaded: 0,
                        },
                    );
                }
            }
        }))
    } else {
        None
    };

    let stdout_log = log_file.clone();
    let app_for_stdout = app.clone();
    let id_for_stdout = id.to_string();
    let stdout_handle = if let Some(stdout) = child.stdout.take() {
        Some(tokio::spawn(async move {
            use tokio::io::AsyncBufReadExt;
            let mut reader = tokio::io::BufReader::new(stdout).lines();
            let mut line_count: u64 = 0;
            while let Ok(Some(line)) = reader.next_line().await {
                line_count += 1;
                if let Ok(mut f) = fs::OpenOptions::new().append(true).open(&stdout_log) {
                    let _ = writeln!(f, "{}", line);
                }
                if line_count % 3 == 0 || line.contains("Complete") || line.contains("Installing") {
                    let mut short_line = line.clone();
                    if short_line.len() > 60 {
                        short_line.truncate(60);
                        short_line.push_str("...");
                    }
                    let simulated_progress = 50 + (line_count.min(180) / 4);
                    let _ = app_for_stdout.emit(
                        "install-progress",
                        InstanceInstallProgress {
                            id: id_for_stdout.clone(),
                            step: format!("NeoForge: {}", short_line),
                            progress: simulated_progress as u64,
                            total_size: None,
                            downloaded: 0,
                        },
                    );
                }
            }
        }))
    } else {
        None
    };

    let status = child
        .wait()
        .await
        .map_err(|e| format!("Failed to wait for NeoForge installer: {}", e))?;

    if let Some(handle) = stderr_handle {
        handle.abort();
    }
    if let Some(handle) = stdout_handle {
        handle.abort();
    }

    if !status.success() {
        return Err("NeoForge installer failed".into());
    }

    let _ = fs::remove_file(&installer_path);
    let _ = fs::remove_file(
        minecraft_dir.join(format!("neoforge-{}-installer.jar.log", neoforge_version)),
    );

    tokio::time::sleep(std::time::Duration::from_millis(1000)).await;

    let _ = app.emit(
        "install-progress",
        InstanceInstallProgress {
            id: id.to_string(),
            step: "Done".into(),
            progress: 100,
            total_size: None,
            downloaded: 0,
        },
    );

    Ok(())
}

pub struct NeoForgeLoader;

impl NeoForgeLoader {
    /// List MC versions that have at least one NeoForge build. Used by the
    /// `get_neoforge_mc_versions` Tauri command.
    pub async fn list_mc_versions() -> Result<Vec<String>, String> {
        let xml = fetch_neoforge_maven_metadata().await?;
        Ok(parse_mc_versions_from_xml(&xml))
    }

    /// List NeoForge builds for a given MC version. Used by the
    /// `get_neoforge_versions` Tauri command. `betas=true` includes
    /// `-beta` suffixed builds.
    pub async fn list_builds(mc_version: &str, betas: bool) -> Result<Vec<String>, String> {
        let xml = fetch_neoforge_maven_metadata().await?;
        Ok(parse_builds_from_xml(&xml, mc_version, betas))
    }
}

#[async_trait]
impl LoaderStrategy for NeoForgeLoader {
    fn engine(&self) -> InstanceEngine {
        InstanceEngine::NeoForge
    }
    fn category(&self) -> LoaderCategory {
        LoaderCategory::Mods
    }
    fn display_name(&self) -> &'static str {
        "NeoForge"
    }
    fn min_java(&self) -> u8 {
        17
    }
    fn capabilities(&self) -> LoaderCapabilities {
        mods_capabilities()
    }

    fn is_two_step_version(&self) -> bool {
        true
    }

    async fn fetch_mc_versions(&self) -> Result<Vec<String>, String> {
        Self::list_mc_versions().await
    }

    async fn fetch_versions(
        &self,
        mc_version: Option<&str>,
    ) -> Result<Vec<VersionMeta>, String> {
        let mc = mc_version
            .ok_or("NeoForge requires an MC version before fetching builds")?;
        let builds = Self::list_builds(mc, true).await?;
        Ok(builds
            .into_iter()
            .map(|b| VersionMeta {
                id: b.clone(),
                build: Some(b.clone()),
                url: None,
                display_name: b,
                requires_mc_version: Some(mc.to_string()),
            })
            .collect())
    }

    async fn resolve_download(&self, version: &VersionMeta) -> Result<DownloadInfo, String> {
        let installer_url = format!(
            "https://maven.neoforged.net/releases/net/neoforged/neoforge/{}/neoforge-{}-installer.jar",
            version.id, version.id
        );
        Ok(DownloadInfo {
            url: installer_url,
            filename: format!("neoforge-{}-installer.jar", version.id),
            size: None,
        })
    }

    async fn install(
        &self,
        app: &tauri::AppHandle,
        id: &str,
        target_dir: &Path,
        version: &VersionMeta,
        _custom_url: Option<&str>,
        accept_eula: bool,
    ) -> Result<(), String> {
        let mc_dir = target_dir.join(".minecraft");
        run_neoforge_installer(app, id, &version.id, &mc_dir).await?;
        write_eula_txt(mc_dir.join("eula.txt"), accept_eula)?;
        Ok(())
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  Forge
// ═══════════════════════════════════════════════════════════════════════════

pub struct ForgeLoader;

#[async_trait]
impl LoaderStrategy for ForgeLoader {
    fn engine(&self) -> InstanceEngine {
        InstanceEngine::Forge
    }
    fn category(&self) -> LoaderCategory {
        LoaderCategory::Mods
    }
    fn display_name(&self) -> &'static str {
        "Forge"
    }
    fn min_java(&self) -> u8 {
        17
    }
    fn capabilities(&self) -> LoaderCapabilities {
        mods_capabilities()
    }

    async fn fetch_versions(
        &self,
        _mc_version: Option<&str>,
    ) -> Result<Vec<VersionMeta>, String> {
        // Delegate to the project-versions shortcut, which already hits the
        // Forge maven-metadata.xml. Mapping to `VersionMeta` keeps the rest of
        // the install pipeline (which reads `url`) working without duplicating
        // the HTTP/regex logic.
        let versions = crate::commands::versions::get_project_versions("forge".to_string()).await?;
        Ok(versions
            .into_iter()
            .map(|combined| {
                // Combined id is "mc_version-forge_version" (e.g.
                // "1.21.11-61.1.14"). The installer URL embeds it twice:
                //   https://maven.minecraftforge.net/net/minecraftforge/forge/{combined}/forge-{combined}-installer.jar
                let mc_version = combined.split('-').next().unwrap_or("").to_string();
                let url = format!(
                    "https://maven.minecraftforge.net/net/minecraftforge/forge/{}/forge-{}-installer.jar",
                    combined, combined
                );
                VersionMeta {
                    id: combined.clone(),
                    build: None,
                    url: Some(url),
                    display_name: combined,
                    requires_mc_version: if mc_version.is_empty() { None } else { Some(mc_version) },
                }
            })
            .collect())
    }

    async fn install(
        &self,
        app: &tauri::AppHandle,
        id: &str,
        target_dir: &Path,
        version: &VersionMeta,
        _custom_url: Option<&str>,
        accept_eula: bool,
    ) -> Result<(), String> {
        // Forge combined version is "mc_version-forge_version"
        // (e.g. "1.20.1-47.2.0"). The installer URL is:
        // https://maven.minecraftforge.net/net/minecraftforge/forge/{ver}/forge-{ver}-installer.jar
        let combined = &version.id;
        let installer_url = format!(
            "https://maven.minecraftforge.net/net/minecraftforge/forge/{}/forge-{}-installer.jar",
            combined, combined
        );
        let mc_dir = target_dir.join(".minecraft");
        fs::create_dir_all(&mc_dir).map_err(|e| e.to_string())?;
        let installer_path = mc_dir.join(format!("forge-{}-installer.jar", combined));
        let log_file = mc_dir.parent().unwrap_or(&mc_dir).join("install.log");

        download_file(app, &installer_url, &installer_path, id, None, Some(&log_file)).await?;

        let _ = app.emit(
            "install-progress",
            InstanceInstallProgress {
                id: id.to_string(),
                step: format!("Ejecutando instalador Forge {}...", combined),
                progress: 50,
                total_size: None,
                downloaded: 0,
            },
        );

        if let Ok(mut f) = fs::OpenOptions::new().append(true).open(&log_file) {
            let _ = writeln!(
                f,
                "[{}] Running Forge installer headlessly...",
                chrono::Local::now().format("%H:%M:%S")
            );
        }

        // Run installer headlessly
        let java_exe = crate::commands::java::find_any_java_executable(app).ok_or_else(|| {
            "Java not found. Install a Java runtime from Settings \u{2192} Portable Java, or set the JAVA_HOME environment variable.".to_string()
        })?;
        let mut std_cmd = std::process::Command::new(&java_exe);
        std_cmd
            .arg("-jar")
            .arg(&installer_path)
            .arg("--installServer")
            .current_dir(&mc_dir)
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped());
        #[cfg(windows)]
        std_cmd.creation_flags(0x08000000);

        let mut cmd = tokio::process::Command::from(std_cmd);
        let mut child = cmd
            .spawn()
            .map_err(|e| format!("Failed to run Forge installer: {}", e))?;

        // Drain stderr — child.stderr.take() prevents the OS pipe buffer
        // (~64KB) from filling up and blocking the child.
        let app_for_stderr = app.clone();
        let id_for_stderr = id.to_string();
        let stderr_log = log_file.clone();
        let stderr_handle = if let Some(stderr) = child.stderr.take() {
            Some(tokio::spawn(async move {
                use tokio::io::AsyncBufReadExt;
                let mut reader = tokio::io::BufReader::new(stderr).lines();
                let mut line_count: u64 = 0;
                while let Ok(Some(line)) = reader.next_line().await {
                    line_count += 1;
                    if let Ok(mut f) = fs::OpenOptions::new().append(true).open(&stderr_log) {
                        let _ = writeln!(
                            f,
                            "[{}] [STDERR] {}",
                            chrono::Local::now().format("%H:%M:%S"),
                            line
                        );
                    }
                    if line_count % 3 == 0
                        || line.contains("Complete")
                        || line.contains("Installing")
                        || line.contains("Downloading")
                        || line.contains("Patching")
                    {
                        let mut short_line = line.clone();
                        if short_line.len() > 60 {
                            short_line.truncate(60);
                            short_line.push_str("...");
                        }
                        let simulated_progress = 50 + (line_count.min(180) / 4);
                        let _ = app_for_stderr.emit(
                            "install-progress",
                            InstanceInstallProgress {
                                id: id_for_stderr.clone(),
                                step: format!("Forge: {}", short_line),
                                progress: simulated_progress as u64,
                                total_size: None,
                                downloaded: 0,
                            },
                        );
                    }
                }
            }))
        } else {
            None
        };

        // Drain stdout — same pattern, no STDERR prefix.
        let stdout_log = log_file.clone();
        let app_for_stdout = app.clone();
        let id_for_stdout = id.to_string();
        let stdout_handle = if let Some(stdout) = child.stdout.take() {
            Some(tokio::spawn(async move {
                use tokio::io::AsyncBufReadExt;
                let mut reader = tokio::io::BufReader::new(stdout).lines();
                let mut line_count: u64 = 0;
                while let Ok(Some(line)) = reader.next_line().await {
                    line_count += 1;
                    if let Ok(mut f) = fs::OpenOptions::new().append(true).open(&stdout_log) {
                        let _ = writeln!(
                            f,
                            "[{}] {}",
                            chrono::Local::now().format("%H:%M:%S"),
                            line
                        );
                    }
                    if line_count % 3 == 0
                        || line.contains("Complete")
                        || line.contains("Installing")
                        || line.contains("Downloading")
                        || line.contains("Patching")
                    {
                        let mut short_line = line.clone();
                        if short_line.len() > 60 {
                            short_line.truncate(60);
                            short_line.push_str("...");
                        }
                        let simulated_progress = 50 + (line_count.min(180) / 4);
                        let _ = app_for_stdout.emit(
                            "install-progress",
                            InstanceInstallProgress {
                                id: id_for_stdout.clone(),
                                step: format!("Forge: {}", short_line),
                                progress: simulated_progress as u64,
                                total_size: None,
                                downloaded: 0,
                            },
                        );
                    }
                }
            }))
        } else {
            None
        };

        let status = child
            .wait()
            .await
            .map_err(|e| format!("Failed to wait for Forge installer: {}", e))?;

        if let Some(handle) = stderr_handle {
            handle.abort();
        }
        if let Some(handle) = stdout_handle {
            handle.abort();
        }

        // NOTE: installer JAR is intentionally NOT removed — keep it around
        // for debug if something goes wrong. NeoForge does delete it, but
        // Forge's install hangs are easier to investigate with the JAR still
        // on disk. Follow-up can re-enable deletion once this is stable.
        if !status.success() {
            return Err("Forge installer failed".into());
        }

        write_eula_txt(mc_dir.join("eula.txt"), accept_eula)?;

        let _ = app.emit(
            "install-progress",
            InstanceInstallProgress {
                id: id.to_string(),
                step: "Done".into(),
                progress: 100,
                total_size: None,
                downloaded: 0,
            },
        );

        Ok(())
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  Fabric
// ═══════════════════════════════════════════════════════════════════════════

pub struct FabricLoader;

#[async_trait]
impl LoaderStrategy for FabricLoader {
    fn engine(&self) -> InstanceEngine {
        InstanceEngine::Fabric
    }
    fn category(&self) -> LoaderCategory {
        LoaderCategory::Mods
    }
    fn display_name(&self) -> &'static str {
        "Fabric"
    }
    fn min_java(&self) -> u8 {
        8
    }
    fn capabilities(&self) -> LoaderCapabilities {
        mods_capabilities()
    }

    async fn fetch_versions(
        &self,
        _mc_version: Option<&str>,
    ) -> Result<Vec<VersionMeta>, String> {
        Err(not_implemented_yet("Fabric"))
    }

    async fn install(
        &self,
        app: &tauri::AppHandle,
        id: &str,
        target_dir: &Path,
        version: &VersionMeta,
        _custom_url: Option<&str>,
        accept_eula: bool,
    ) -> Result<(), String> {
        // version.id is the combined "mc+loader" (e.g. "1.20.1+0.15.6").
        // Server launcher JAR: meta.fabricmc.net/v2/versions/loader/{combined}/server/jar
        let url = format!(
            "https://meta.fabricmc.net/v2/versions/loader/{}/server/jar",
            version.id
        );
        let mc_dir = target_dir.join(".minecraft");
        fs::create_dir_all(&mc_dir).map_err(|e| e.to_string())?;
        let jar_path = mc_dir.join("fabric-server-launch.jar");
        let log_file = mc_dir.parent().unwrap_or(&mc_dir).join("install.log");

        download_file(app, &url, &jar_path, id, None, Some(&log_file)).await?;
        write_eula_txt(mc_dir.join("eula.txt"), accept_eula)?;

        let _ = app.emit(
            "install-progress",
            InstanceInstallProgress {
                id: id.to_string(),
                step: "Done".into(),
                progress: 100,
                total_size: None,
                downloaded: 0,
            },
        );
        Ok(())
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  Quilt
// ═══════════════════════════════════════════════════════════════════════════

pub struct QuiltLoader;

#[async_trait]
impl LoaderStrategy for QuiltLoader {
    fn engine(&self) -> InstanceEngine {
        InstanceEngine::Quilt
    }
    fn category(&self) -> LoaderCategory {
        LoaderCategory::Mods
    }
    fn display_name(&self) -> &'static str {
        "Quilt"
    }
    fn min_java(&self) -> u8 {
        8
    }
    fn capabilities(&self) -> LoaderCapabilities {
        mods_capabilities()
    }

    async fn fetch_versions(
        &self,
        _mc_version: Option<&str>,
    ) -> Result<Vec<VersionMeta>, String> {
        Err(not_implemented_yet("Quilt"))
    }

    async fn install(
        &self,
        app: &tauri::AppHandle,
        id: &str,
        target_dir: &Path,
        version: &VersionMeta,
        _custom_url: Option<&str>,
        accept_eula: bool,
    ) -> Result<(), String> {
        // Quilt's server launcher mirrors Fabric's API: meta.quiltmc.org
        let url = format!(
            "https://meta.quiltmc.org/v2/versions/loader/{}/server/jar",
            version.id
        );
        let mc_dir = target_dir.join(".minecraft");
        fs::create_dir_all(&mc_dir).map_err(|e| e.to_string())?;
        let jar_path = mc_dir.join("quilt-server-launch.jar");
        let log_file = mc_dir.parent().unwrap_or(&mc_dir).join("install.log");

        download_file(app, &url, &jar_path, id, None, Some(&log_file)).await?;
        write_eula_txt(mc_dir.join("eula.txt"), accept_eula)?;

        let _ = app.emit(
            "install-progress",
            InstanceInstallProgress {
                id: id.to_string(),
                step: "Done".into(),
                progress: 100,
                total_size: None,
                downloaded: 0,
            },
        );
        Ok(())
    }
}
